module.exports = {
  CSE: "cse",
  ECE: "ece",
  MECH: "mech",
  IT: "it",
  CIVIL: "civil",
  EEE: "eee",
  MCA: "mca",
  MBA: "mba",
  MTECH: "mtech",
  AIML: "aiml",
  "CSE-AIML": "cse-aiml",
  "CSE-DS": "cse-ds",
  "CSE-CS": "cse-cs",
  "CSE-IOT": "cse-iot",
  "CSE-CYBER": "cse-cyber",
};
